### ISSUE TITLE
Fix SHA256 

### ISSUE THREAD

**Issue by NicolasGuilloux** [clefru/nur-packages#1]
Hi there !

Since Parsec updated his package, the hash is no longer valid. The new one appears to be `0xbq87sz88ldisl65cpcpza2hqjr5y9npn2lmkznzb5qcjd99i5f`. Do you mind changing it?

Thanks ! :)

**Comment by clefru** [comment]
Thanks for the heads up, but s3 seems to still serve me the old file:
$ nix-prefetch-url https://s3.amazonaws.com/parsec-build/package/parsec-linux.deb                
path is '/nix/store/8x1vgzlawi6hsmfjnfq79nw34r1xnzyv-parsec-linux.deb'
1hfdzjd8qiksv336m4s4ban004vhv00cv2j461gc6zrp37s0fwhc

Can you try that command and see if it results in the same sha256?

**Comment by bluemage650** [comment]
Hi @clefru 
Definitely getting a different hash here too, but only with the nur.repos version for some reason. 
```
$ nix-prefetch-url https://s3.amazonaws.com/parsec-build/package/parsec-linux.deb
[3.0 MiB DL]
path is '/nix/store/8x1vgzlawi6hsmfjnfq79nw34r1xnzyv-parsec-linux.deb'
1hfdzjd8qiksv336m4s4ban004vhv00cv2j461gc6zrp37s0fwhc
```
When using nur.repos.clefru.parsecgaming:
```
hash mismatch in fixed-output derivation '/nix/store/8x1vgzlawi6hsmfjnfq79nw34r1xnzyv-parsec-linux.deb':
  wanted: sha256:0xbq87sz88ldisl65cpcpza2hqjr5y9npn2lmkznzb5qcjd99i5f
  got:    sha256:1hfdzjd8qiksv336m4s4ban004vhv00cv2j461gc6zrp37s0fwhc
```
But it works if I just manually import the raw package. NUR might be out of date somehow?

**Comment by clefru** [comment]
I clean up my repo a bit, and make it pass on travis. The nur-combined repo has updated by now. Could you check if parsecgaming works for you now? Also delroth has a parsecgaming in his nur repo.

**Comment by NicolasGuilloux** [comment]
Woups, sorry I did not see your answer. Yeap' everything seems fine now thank :)
