### ISSUE TITLE
Parsec only gets networking as root

### ISSUE THREAD

**Issue by MatthewCroughan** [clefru/nur-packages#2]
https://github.com/clefru/nur-packages/tree/master/pkgs/parsecgaming

When running `parsecgaming` as root, logging in, connecting and more works fine.

If running `parsecgaming` as a user, the app will return `"Failed to request v1 auth. Please check your internet connection" error 800` when trying to log in and use Parsec.

**Comment by RaghavSood** [comment]
This is due to Parsec deprecating and shutting off `api.parsecgaming.com`.

The default deb downloaded from Parsec contains `parsecd-150-28.so`, which still attempts to connect to the old API.

When you run Parsec the first time, it will download `parsecd-150-50.so` into `$HOME/.parsec`.

You will then need to shut down parsec, and edit `$HOME/.parsec/appdata.json` to point to the new version, as well as updating its `sha256sum` value to match the new version.

I've raised an issue in their discord about shipping the debian installers with a newer version of `parsecd`, but they haven't confirmed if they will do it.

**Comment by MatthewCroughan** [comment]
@RaghavSood Thank you so much for that explanation, wonderful. But how come it still works as root? Root has the same scenario occuring, as can be seen in `.parsec/`.

I'm looking into using Moonlight game streaming since it looks like it's better supported on Nix, and is more sustainable/open source anyway.

**Comment by RaghavSood** [comment]
My suspicion is that Parsec's default update approach of downloading the newer library and then pointing the main electron(?) app to it doesn't work on Nix when run as a regular user, possibly because it might be trying to update something in the nix store.

Running as root might allow it to do that, although it may break other stuff if it breaks assumptions that Nix makes about files being handled by Nix.

I eventually settled on this by running `strace` and starting it manually to verify it was connecting to `api.parsecgaming.com`, and then updating the library manually - after doing that, `strace` showed no connections to the old endpoints, and its been pretty stable since then

**Comment by RaghavSood** [comment]
https://discord.com/channels/275729591505780736/275735607962107904/777126601150038017

I raised this issue in discord yesterday, got a general "we'll see if we can update the debian packages to ship with a newer library" response, so we'll see how that goes

**Comment by delroth** [comment]
FYI if that's useful, you can get the latest appdata.json at https://builds.parsecgaming.com/channel/release/appdata/linux/latest and fetch the associated .so from e.g. https://builds.parsecgaming.com/channel/release/binary/linux/gz/parsecd-150-50.so . I've modified my custom Parsec derivation to directly fetch and patchelf that .so and it's working great for me.

**Comment by clefru** [comment]
@delroth Thanks for the workaround. Do you want to maybe create a NUR, so people can fetch your pkgs easily?

Here is delroth's pkg for people to try:
```
(import <nixpkgs> {}).callPackage (builtins.fetchurl "https://raw.githubusercontent.com/delroth/infra.delroth.net/master/pkgs/parsec.nix") {}
 ```

Alternatively with my package, you can use this workaround:
```
mkdir ~/.parsec
cd ~/.parsec
rm appdata.json
wget -O appdata.json https://builds.parsecgaming.com/channel/release/appdata/linux/latest
wget https://builds.parsecgaming.com/channel/release/binary/linux/gz/$(cat appdata.json | nix-shell -p jq --run "jq -r .so_name")
```
with this package. You probably only have to run this once.

I sadly don't use Parsec anymore. So I will probably just mark this package broken.

**Comment by MatthewCroughan** [comment]
@clefru Do you now use an alternative? If so, what is it?

**Comment by LorenzWieseke** [comment]
> FYI if that's useful, you can get the latest appdata.json at https://builds.parsecgaming.com/channel/release/appdata/linux/latest and fetch the associated .so from e.g. https://builds.parsecgaming.com/channel/release/binary/linux/gz/parsecd-150-50.so . I've modified my custom Parsec derivation to directly fetch and patchelf that .so and it's working great for me.

I can't download the .so file, maybe they moved to s3 / aws ? Does anyone know where to get the current version ? The appdata is sayig it's 150-78.

**Comment by clefru** [comment]
`wget https://builds.parsecgaming.com/channel/release/binary/linux/gz/parsecd-150-78.so` works just fine for me.

**Comment by clefru** [comment]
@MatthewCroughan I moved my gaming PC next to my workstation and hooked it up physical. Parsec just isn't fast enough for more than 1080p. Also with Steam supporting many games via Proton, the need for Parsec just decreased drastically.

**Comment by LorenzWieseke** [comment]
Thanks for the response, I tried to lunch parsec and now I get 👍 
/home/pi/.parsec/parsecd-150-78.so: wrong ELF class: ELFCLASS64
I'm on the rasberry pi 3 / raspian bullseye

**Comment by MatthewCroughan** [comment]
> Thanks for the response, I tried to lunch parsec and now I get +1 /home/pi/.parsec/parsecd-150-78.so: wrong ELF class: ELFCLASS64 I'm on the rasberry pi 3 / raspian bullseye

That is trying to tell you that the static object (`.so`) you're trying to execute is not compiled for the correct architecture. You are trying to run x86_64 code on an ARM device (Raspberry Pi 3).

**Comment by LorenzWieseke** [comment]
so is there any way of getting parsec to run on a pi 3 ? Using the default way I get this v1 auth error (-800 no internet connection)

been trying for days now, on pi3 and 4 but no chance

**Comment by MatthewCroughan** [comment]
> so is there any way of getting parsec to run on a pi 3 ? Using the default way I get this v1 auth error (-800 no internet connection)

Not unless you make your own derivation to support ARM. I'm sick of this crappy proprietary software, so I won't be doing that :D

**Comment by LorenzWieseke** [comment]
so to make it clear for me, they made a 32 bit arm build and published it for the pi 3 (as described here : https://support.parsec.app/hc/en-us/articles/115002699012-Setting-Up-On-Raspberry-Pi-Raspbian-) but that deb file uses an old .so file that tries to call some old api that doesn't exist anymore ?

**Comment by LorenzWieseke** [comment]
because parsec isn't open source noone compiled another arm version and I really tried everything, raspbian, ubuntu, android and kodi (which worked but not on widescreen)

**Comment by MatthewCroughan** [comment]
They did compile an arm version here https://s3.amazonaws.com/parsec-build/package/parsec-rpi.deb, but you're not going to have a good time with this software because it is proprietary. Every few months you will get an error with this Nix derivation, because the source code will have changed its contents at the same url. So next month, the sha256 of the link I shared above will change, which will cause the derivation to fail.

**Comment by not-important-vr** [comment]
> so to make it clear for me, they made a 32 bit arm build and published it for the pi 3 (as described here : https://support.parsec.app/hc/en-us/articles/115002699012-Setting-Up-On-Raspberry-Pi-Raspbian-) but that deb file uses an old .so file that tries to call some old api that doesn't exist anymore ?

Use this link for the pi version and replace it with appdata.json in $HOME/.parsec:
https://builds.parsecgaming.com/channel/release/appdata/rpi/latest

Currently the latest .so is this one, put it into the same folder as above:
https://builds.parsecgaming.com/channel/release/binary/rpi/gz/parsecd-150-47.so

I also did chmod +x for both files just in case and it works now.

**Comment by gillenlaxalt** [comment]
> > so to make it clear for me, they made a 32 bit arm build and published it for the pi 3 (as described here : https://support.parsec.app/hc/en-us/articles/115002699012-Setting-Up-On-Raspberry-Pi-Raspbian-) but that deb file uses an old .so file that tries to call some old api that doesn't exist anymore ?
> 
> Use this link for the pi version and replace it with appdata.json in $HOME/.parsec: https://builds.parsecgaming.com/channel/release/appdata/rpi/latest
> 
> Currently the latest .so is this one, put it into the same folder as above: https://builds.parsecgaming.com/channel/release/binary/rpi/gz/parsecd-150-47.so
> 
> I also did chmod +x for both files just in case and it works now.

Sir, your answer has provided me a solution, you rock !

**Comment by clefru** [comment]
I fixed up the parsec package to at least work for me under x86_64. However, since I am not really using parsec on a regular basis, it will probably go stale again. It would be best if it is moved to a different repo of someone using it regularly.

As to the original issue, root is certainly not required for networking, so I am closing this issue. I presume that this observation was just a side effect of resetting ~/.parsec.

**Comment by MatthewCroughan** [comment]
@clefru I just use the official nixos package for parsec in my config nowadays.

https://github.com/MatthewCroughan/nixcfg/commit/5632df7d4e9ae9cfb53b3b3e27bce308c4558e22

**Comment by srosato** [comment]
> Failed to request v1 auth. Please check your internet connection" error 800

On my side, after downloading the latest version, I would get this error until I deleted `~/.parsec` as it was pretty old and now it works again (using PopOS as distribution)
