### ISSUE TITLE
Parsec Error -32001	"SCTP_ERR_WRITE"

### ISSUE THREAD

**Issue by RollSteel** [clefru/nur-packages#3]
Hello everyone, I have a problem with Parsec where when a friend connects to the PC using the Parsec Web App, after 3 minutes of connecting to me, he gives him error and gives me error --32001 and I have seen on the Parsec website a solution or a description of the error but it is written only "SCTP_ERR_WRITE" what does this mean? How can I solve the problem? (Unfortunately my friend cannot download the Parsec software)

**Comment by clefru** [comment]
Sorry, I have no idea. Contact Parsec on their Discord. Also the packaging I provide here is entirely unsupported and probably broken, because I stopped using Parsec.

**Comment by RollSteel** [comment]
Hi, thank you very much for the reply due 2 years ago, I forgot to say that I solved it because at the time the Parsec integration was pitiful by not forwarding the port correctly because my friend used the Power Line to get the internet signal to him from afar from modem to PC, thanks again
